functions:
  requestHandler:
    handler: api/index.handler
    memorySize: 1024
    timeout: 15
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      # ... your environment variables

  installHandler:
    handler: api/install.handler
    memorySize: 1024
    timeout: 30  # Set a higher timeout for the installation path
    events:
      - httpApi:
          method: any
          path: /wp-admin/install.php
    environment:
      #DATABASE: ''
      #USERNAME: ''
      #PASSWORD: Don't set this if you'll be commiting the file, instead use the AWS console or another method like Parameter Store
      #HOST: ''